version: '3.7'
services:
  cm-app:
    image: cm-app
    build: ./
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
